### PR TITLE
Update MainMenuState.hx

### PR DESCRIPTION
**Pull request by Jkselle**

### CODE REVIEW

**Comment by ImaginationSuperHero528** [comment]
Wtf?

**Comment by pasta870** [comment]
Screenshot_20220625-054009_YouTube

**Comment by ImaginationSuperHero528** [comment]
@jigsaw-4277821 don't accept it they basically broke (I think) the hx file.

**Comment by InsKal** [comment]
this is literally a custom main menu, but literally i think this is broken.

**Pull request closed without merging**
